Iter5
alexeyvilmost/urlshort pull request #1
Opened 2023-11-12 17:54 UTC by alexeyvilmost

2023-11-16 15:19 UTC, s-shpak requested changes
Перенеси всю логику в `internal` в cmd должна остаться только точка входа с минимальной логикой запуска

2023-11-16 15:19 UTC, s-shpak commented on go.mod
Надо обновить при помощи `go mod tidy`

2023-11-16 15:19 UTC, s-shpak commented on cmd/shortener/main.go
> +var mainPtr *string
Глобальные переменные не нужны

2023-11-16 15:19 UTC, s-shpak commented on cmd/shortener/main.go
> +	mainPtr = flag.String("a", "localhost:8080", "Base host adress")
Убери получение конфигурации в отдельную функцию, она должна возвращать объект конфигурации со всеми параметрами

2023-11-16 15:19 UTC, s-shpak commented on cmd/shortener/main.go
> +	// if mainHost == resultHost {
Такие комменты - deadcode, их в PR не должно быть

2023-11-16 15:19 UTC, s-shpak commented on cmd/shortener/main.go
> +	log.Fatal(http.ListenAndServe(mainHost, r))
Даже если ошибка будет `nil` процесс будет завершаться с ненулевым кодом (то есть с ошибкой)

2023-11-16 15:19 UTC, s-shpak commented on cmd/shortener/handlers.go
> +		panic(err)
Паники не надо использовать вообще и тем более в глубине кода. Здесь надо залогировать ошибку и вернуть пользователю `Internal server error`

2023-11-16 15:19 UTC, s-shpak commented on cmd/shortener/handlers.go
> +	storage[short] = string(url.URL)
Что если в storage такая короткая ссылка уже есть ?

2023-11-16 15:19 UTC, s-shpak commented on cmd/shortener/handlers.go
> +		http.Error(res, "Не удалось распарсить запрос", http.StatusBadRequest)
Кажется, что это нештатная ошибка и ее надо логировать

2023-11-16 15:19 UTC, s-shpak commented on cmd/shortener/handlers.go
> +func shortener(res http.ResponseWriter, req *http.Request) {
А нельзя ли как-то вынести общую логику в этой и предыдущей функции в одну функцию и обащаться к ней ?

2023-11-16 15:19 UTC, s-shpak commented on cmd/shortener/handlers.go
> +	fmt.Println(chi.URLParam(req, "short_url"))
Если ты что-то логируешь, то это надо делать через `log`

2023-11-16 15:19 UTC, s-shpak commented on cmd/shortener/handlers.go
> +func balancer(res http.ResponseWriter, req *http.Request) {
Тебе это не нужно, т.к. ты используешь `chi`, он роутит запросы самостоятельно

2023-11-16 15:19 UTC, s-shpak commented on cmd/shortener/storage.go
> +var storage = map[string]string{}
Глобальные перменные не нужны

2023-11-18 05:56 UTC, alexeyvilmost commented on cmd/shortener/main.go
> +var mainPtr *string
Исправлено

2023-11-18 05:56 UTC, alexeyvilmost commented on cmd/shortener/main.go
> +	mainPtr = flag.String("a", "localhost:8080", "Base host adress")
Исправлено

2023-11-18 05:56 UTC, alexeyvilmost commented on cmd/shortener/main.go
> +	// if mainHost == resultHost {
Исправлено

2023-11-18 05:58 UTC, alexeyvilmost commented on cmd/shortener/main.go
> +	log.Fatal(http.ListenAndServe(mainHost, r))
Исправлено

2023-11-18 05:59 UTC, alexeyvilmost commented on cmd/shortener/handlers.go
> +		panic(err)
Исправлено

2023-11-18 05:59 UTC, alexeyvilmost commented on cmd/shortener/handlers.go
> +	storage[short] = string(url.URL)
Исправлено

2023-11-18 05:59 UTC, alexeyvilmost commented on cmd/shortener/handlers.go
> +		http.Error(res, "Не удалось распарсить запрос", http.StatusBadRequest)
Исправлено

2023-11-18 05:59 UTC, alexeyvilmost commented on cmd/shortener/handlers.go
> +func shortener(res http.ResponseWriter, req *http.Request) {
Исправлено

2023-11-18 05:59 UTC, alexeyvilmost commented on cmd/shortener/handlers.go
> +	fmt.Println(chi.URLParam(req, "short_url"))
Исправлено

2023-11-18 05:59 UTC, alexeyvilmost commented on cmd/shortener/handlers.go
> +func balancer(res http.ResponseWriter, req *http.Request) {
Исправлено

2023-11-18 05:59 UTC, alexeyvilmost commented on cmd/shortener/storage.go
> +var storage = map[string]string{}
Исправлено

2023-11-18 06:00 UTC, alexeyvilmost commented on go.mod
Исправлено

2023-11-18 18:59 UTC, s-shpak requested changes

2023-11-18 18:59 UTC, s-shpak commented on cmd/shortener/main.go
> +func StartServer() {
Это не совсем корректно: тут ты не только стартуешь сервер, но еще и парсишь конфигурацию. Давай уберем регистрацию роутера и старт сервера в `internal`, конфигурацию тоже туда, но в отдельный файл (или даже пакет). Плюс если в функции может возникнуть ошибка, функция должна ее возвращать.

`log.Fatal`, таким образом, стоит вызывать в `main`

2023-11-18 18:59 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +	result := new(Handlers)
result := &Hanlders {

}
```suggestion
	result := &Handlers{
	BaseURL: ...,
	}
```

2023-11-18 18:59 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +		log.Println("Не удалось распарсить запрос")
Ошибку тоже желательно залогировать

2023-11-18 18:59 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +		log.Println(k, ": ", v)
Это не нужно

2023-11-18 18:59 UTC, s-shpak commented on internal/app/utils/config.go
> +func DefaultConfig() *Config {
Дефолтные значения уже есть на строках 15-16

2023-11-18 18:59 UTC, s-shpak commented on internal/app/utils/utils.go
> +func GenerateShortKey(storage *map[string]string) string {
Не стоит делать два действия сразу: генерирую ключ в одной функции, а записывай его в другой

2023-11-20 13:10 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +	short := utils.GetUniqueShortKey(&h.Storage)
Это неудобно, т.к. между проверкой и записью значения в БД такое значение может появиться в базе, и произойдет коллизия. Лучше делать так:
1. генерируешь значение
2. пытаешься его записать в Storage
3. если такого значения нет, то оно записывается корректно
4. если такое зачение есть, то Storage возвращает специфическую ошибку, которая на это указывает. Ты возвращаешься к пункту 1 в этом случае

2023-11-20 13:11 UTC, s-shpak requested changes
См. последний комментарий

2023-11-20 17:00 UTC, alexeyvilmost commented on internal/app/handlers/handlers.go
> +	short := utils.GetUniqueShortKey(&h.Storage)
Исправлено

2023-11-21 16:55 UTC, s-shpak approved these changes

2023-11-21 17:51 UTC, merged