Iter9
alexeyvilmost/urlshort pull request #2
Opened 2023-12-18 12:32 UTC by alexeyvilmost

2023-12-20 22:17 UTC, s-shpak requested changes
1. Я не обратил на это внимание на прошлом ревью, но что если в файле `internal/app/handlers/handlers.go` на строке 53 вернется ошибка отличная от `ErrDuplicateValue` ? Как обраотать эту ситуацию ?
2. Добавь, пожалуйста, линтер в свой проект. Здесь описано, как это сделать: https://github.com/s-shpak/praktikum-golangci-lint?tab=readme-ov-file#настройка-github-actions
Ты можешь сконфигурировать его как тебе удобно, хотя конифгурация в репозитории кажется мне адекватной. Ты можешь не делать это, т.к. в курсе нет такого требования, но линтер позволит тебе отлавливать большое количество механических ошибок

2023-12-20 22:17 UTC, s-shpak commented on cmd/shortener/storage.st
Что это за файл ? Если в нем хранились данные, то его надо убрать из репозитория

2023-12-20 22:17 UTC, s-shpak commented on cmd/shortener/storage.txt
Этот файл надо убрать из репозитория

2023-12-20 22:17 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +func ReadCompressed(req *http.Request) (io.Reader, error) {
Этот функционал также должен находиться в `middleware`

2023-12-20 22:17 UTC, s-shpak commented on internal/app/logging/logging.go
> +	logFn := func(w http.ResponseWriter, r *http.Request) {
Нет смысла инициализировать здесь новую переменную, лучше сразу возвращай эту функцию

2023-12-20 22:17 UTC, s-shpak commented on internal/app/server/server.go
> +	r.Post("/", logging.WithLogging(handlers.Shortener))
Для подключения `middleware` в `chi` лучше использовать https://pkg.go.dev/github.com/go-chi/chi#Mux.Use

2023-12-20 22:17 UTC, s-shpak commented on internal/app/server/server.go
> +	zerolog.SetGlobalLevel(zerolog.DebugLevel)
Почему у тебя захардкожен здесь `DebugLevel` ?

2023-12-20 22:17 UTC, s-shpak commented on internal/app/storage/storage.go
> +	file, err := os.Create(filename)
Что если `filename` пустой ? Пользователь может отключить запись данных в файл. Что если ошибка будет связана не с тем, что пользователь хочет отключить запись в файл.

Кроме того пустой `filename` не должен приводить к ошибке, это штатная ситуация

2023-12-20 22:17 UTC, s-shpak commented on storage.txt
Этот файл надо убрать из репозитория

2023-12-20 22:17 UTC, s-shpak commented on temp
Этот файл надо убрать из репозитория

2023-12-20 22:17 UTC, s-shpak commented on internal/app/storage/storage.go
> +	s.file.WriteString(shortURL + " : " + fullURL)
Этот метод возвращает ошибку. Ее надо проверить и правильно обработать

2023-12-26 14:07 UTC, alexeyvilmost commented on internal/app/handlers/handlers.go
> +func ReadCompressed(req *http.Request) (io.Reader, error) {
Переместил в utils

2023-12-26 23:52 UTC, s-shpak commented on internal/app/server/server.go
> +	r.Post("/", logging.WithLogging(handlers.Shortener))
Это не сделано

2023-12-26 23:53 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +func ReadCompressed(req *http.Request) (io.Reader, error) {
Нет, этот функционал должен быть в middleware, так, чтобы разжатие и сжатие сообщения происходило перед и после его обработки соответственно

2023-12-27 00:04 UTC, s-shpak requested changes
Линер пока не добавлен. Если у тебя нет времени исправлять его замечания сейчас, то добавь его все равно, а код поправишь в следующем спринте

2023-12-27 00:04 UTC, s-shpak commented on internal/app/storage/storage.go
> +		log.Error().Msg(err.Error())
Кажется, что если здесь возникла ошибка, мы не можем продолжать выполнение программы. Необходимо вернуть эту ошибку наверх, залогировать ее и корректно завершиться

2023-12-27 00:04 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +	if err != nil {
Тебе надо разобраться, как работать с ошибками:
1. ошибки надо корректно обрабатывать: если твоя ошибка не `nil`, то ты не можешь пользоваться `shortURL`, т.к. она не сохранена. Значит, эта функция должна возвращать ошибку, которая будет проверяться вовне. Далее эту ошибку надо как-то обработать: вернуть пользователю либо 409, либо 500
2. ошибки, в общем случае, проверяются не через `==`, а при помощи `errors.Is()`. Для того, чтобы корректно обернуть ошибку можно использовать подобную конструкцию: `fmt.Errorf("failed to do something: %w", err)`. Здесь можно почитать подробнее:  https://go.dev/blog/go1.13-errors

2024-01-11 12:23 UTC, alexeyvilmost commented on internal/app/handlers/handlers.go
> +	if err != nil {
Исправлено

2024-01-11 12:28 UTC, alexeyvilmost commented on internal/app/storage/storage.go
> +		log.Error().Msg(err.Error())
Исправлено

2024-01-11 12:29 UTC, alexeyvilmost commented on internal/app/server/server.go
> +	r.Post("/", logging.WithLogging(handlers.Shortener))
Исправлено

2024-01-11 16:03 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +	if err != nil {
Ошибку надо проверять при помощи `errors.Is`, а не `==`

2024-01-11 16:04 UTC, s-shpak requested changes
См. последний комменатрий

2024-01-12 08:13 UTC, alexeyvilmost commented on internal/app/handlers/handlers.go
> +	if err != nil {
Исправлено

2024-01-12 09:24 UTC, s-shpak approved these changes

2024-01-12 09:39 UTC, merged