Iter13
alexeyvilmost/urlshort pull request #3
Opened 2024-01-21 23:34 UTC by alexeyvilmost

2024-01-23 12:36 UTC, s-shpak requested changes

2024-01-23 12:36 UTC, s-shpak commented on cmd/shortener/storDage.txt
Этот файл не стоит пушить в репозиторий

2024-01-23 12:36 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +			res.WriteHeader(http.StatusInternalServerError)
В случае Internal Server Error ошибку стоит залогировать

2024-01-23 12:36 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +		http.Error(res, "Внутренняя ошибка: "+err.Error(), http.StatusInternalServerError)
А здесь ошибку нельзя отдавать пользователю, т.к. это внутренняя ошибка сервиса. Зато ее можно залогировать

2024-01-23 12:36 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +		http.Error(res, "Соединение с БД отсутствует", http.StatusBadRequest)
Мне кажется, что это InternalServerError

2024-01-23 12:36 UTC, s-shpak commented on internal/app/storage/storage.go
> +var ErrExistingFullURL = errors.New("Addition attempt failed: full url already exists")
```suggestion
var ErrExistingFullURL = errors.New("addition attempt failed: full url already exists")
```

2024-01-23 12:36 UTC, s-shpak commented on internal/app/storage/storage.go
> +	log.Debug().Msg("ConnString: " + config.DBString)
Не стоит логировать DSN: там может быть конфиденциальная информация

2024-01-23 12:36 UTC, s-shpak commented on internal/app/storage/storage.go
> +		_, err = db.Exec("CREATE TABLE IF NOT EXISTS urls (short_url TEXT UNIQUE, full_url TEXT, PRIMARY KEY (short_url));")
Это необходимо делать при помощи механизма миграций. Если не успеваешь, то вынесем это в технический долг, надо будет сделать на итоговом проекте и на итерации после него

2024-01-23 12:36 UTC, s-shpak commented on internal/app/storage/storage.go
> +func (s *Storage) Get(shortURL string) (string, bool, error) {
Лучше не добавлять дополнительное возвращаемое значение, а передавать информацию об отсутствии записи при помощи ошибки

2024-01-23 12:36 UTC, s-shpak commented on main
Это надо удалить из репозитория

2024-01-23 12:36 UTC, s-shpak commented on shortener
Это надо удалить из репозитория

2024-01-24 00:56 UTC, alexeyvilmost commented on internal/app/storage/storage.go
> +		_, err = db.Exec("CREATE TABLE IF NOT EXISTS urls (short_url TEXT UNIQUE, full_url TEXT, PRIMARY KEY (short_url));")
Давайте сейчас вынесем это в техдолг. Поделитесь best practice по использованию миграций в Go? В теории эта тема не раскрыта (точнее, вообще не упомянута с: )

2024-01-24 12:01 UTC, s-shpak commented on internal/app/storage/storage.go
> +		_, err = db.Exec("CREATE TABLE IF NOT EXISTS urls (short_url TEXT UNIQUE, full_url TEXT, PRIMARY KEY (short_url));")
Мы это разбирали на вебинаре. Запись и материалы к нему можно найти здесь:
- https://app.pachca.com/chats/7364297?message=107181896
- https://app.pachca.com/chats/7364297?message=108266622

2024-01-24 13:15 UTC, s-shpak requested changes

2024-01-24 13:15 UTC, s-shpak commented on .DS_Store
Этот файл не надо пушить в репозиторий

2024-01-25 12:26 UTC, s-shpak approved these changes

2024-01-25 12:36 UTC, merged